import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import { useSession, signIn, signOut } from 'next-auth/react';
import useSWR from 'swr';

export default function Home() {
  const { data: session } = useSession();
  const { data } = useSWR(session ? ['/api/user'] : null);
  console.log({ data });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            {!session ? (
              <button
                className={styles.card}
                onClick={() => {
                  signIn();
                }}
              >
                Sign In
              </button>
            ) : (
              <button
                className={styles.card}
                onClick={() => {
                  signOut();
                }}
              >
                Sign Out
              </button>
            )}
          </div>
        </div>

        <div>
          <p>
            <code className={styles.code}>Next-Authjs Session Data</code>
          </p>
        </div>
        <div className={styles.description}>
          <p>
            <code className={styles.code}>{session ? JSON.stringify(session) : ''}</code>
          </p>
        </div>

        <div className={styles.center}>
          <Image className={styles.logo} src="/next.svg" alt="Next.js Logo" width={180} height={37} priority />
          <div className={styles.thirteen}>
            <Image src="/thirteen.svg" alt="13" width={40} height={31} priority />
          </div>
        </div>
      </main>
    </>
  );
}
